DROP TABLE IF EXISTS `Product`;

CREATE TABLE `Product` (
  `id` INT UNIQUE PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `image_file` VARCHAR(255) DEFAULT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `price` VARCHAR(10) NOT NULL,
  `stock_quantity` INT NOT NULL
);

DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
  `id` INT UNIQUE PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `hashed_password` VARCHAR(255) NOT NULL,
  `birthdate` DATE NOT NULL,
  `gender` BOOLEAN NOT NULL,
  `profile_picture_file` VARCHAR(255) DEFAULT NULL,
  `is_admin` BOOLEAN NOT NULL DEFAULT 0
);