DROP TABLE IF EXISTS `Product`;

CREATE TABLE `Product` (
  `id` INT UNIQUE PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `price` VARCHAR(10) NOT NULL,
  `stock_quantity` INT NOT NULL
);

DROP TABLE IF EXISTS `User`;

CREATE TABLE `User` (
  `id` INT UNIQUE PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL DEFAULT 0
);